---
title: "Limites"
subtitle: "Anotações das aulas"
knitr:
  opts_chunk:
    echo: false
format: html
---
```{r}
library(ggplot2)
```

### Aula 5 - Técnicas para o cálculo de limites

1. Intuição

2. Limites laterais (muito útil quando tem módulo)


3. Fatoração

  - $a^2 - b^2 = (a+b)(a-b)$
  
  - $a^3 - b^3 = (a-b)(a^2 + ab + b^2)$ 

4. Racionalização (destruir raízes!)

5. [Teorema da função limitada](lim-funcao-limitada.qmd)

6. [Primeiro limite fundamental do cálculo](lim-fundamental-senx-x.qmd)

7. Polinômios: 

  - $\lim_{x \to + \infty} P_{n} (x)$ ou $\lim_{x \to - \infty} P_{n} (x)$: deixar em evidência a potência de maior grau, quando houver um limite de polinômio com x tendendo à mais ou menos infinito.
  
  - $\lim_{x \to + \infty} \frac{P_{n} (x)}{Q_{m} (x)}$ ou $\lim_{x \to - \infty} \frac{P_{n} (x)}{Q_{m} (x)}$: dividir todos os termos do polinômio pelo termo de maior grau. Simplificar o que dá: a maior potência em comum em cima e em baixo.

8. Segundo limite fundamental do cálculo

9. Uso de derivadas

## Aula 4 - Exemplos:

```{js}
window.MathJax = {
  loader: {load: ['[tex]/cancel']},
  tex: {packages: {'[+]': ['cancel']}}
};
window.MathJax = {
  loader: {load: ['[tex]/cancel']},
  tex: {packages: {'[+]': ['cancelto']}}
};
window.MathJax = {
  loader: {load: ['[tex]/color']},
  tex: {packages: {'[+]': ['color']}}
};
```

### Exemplo 1:

$$
\lim_{x \to 0} \frac{1}{x^2} . x^2 = 
\lim_{x \to 0} \frac{1}{\cancel{x^2}} . \cancel{x^2} = 1
$$

### Exemplo 2:


$$
\lim_{x \to 0} \frac{1}{x^2} . x^4 =
\lim_{x \to 0} \frac{1}{\cancel{x^2}} . x^{\cancel{4} \rightarrow 2}
= \lim_{x \to 0} \frac{1}{1} . x^{2} 
= \lim_{x \to 0} \cancelto{0}{x^{2}} = 0
$$


### Exemplo 3:


$$
\lim_{x \to 0} \frac{1}{x^4} . x^2
= \lim_{x \to 0} \frac{1}{x^{\cancel{4} \rightarrow 2}} . \cancel{x^2} 
= \lim_{x \to 0} \frac{1}{x^{2}}
= +\infty
$$

::: {.callout-important}
A intuição da última etapa é: $x^2$, com $x$ tendendo a zero, é um número muito pequeno. 1 dividido por um número muito pequeno é um número muito grande. Portanto, o limite é infinito positivo.
:::



### Exemplo 4:

$$
\lim_{x \to 0} \frac{1}{x^2} . x =
\lim_{x \to 0} \frac{1}{x^{\cancel{2} \rightarrow 1 }} . \cancel{x} =
\lim_{x \to 0} \frac{1}{x} \Rightarrow
 \nexists \lim_{x \to 0} \frac{1}{x}
$$

Lembrando que [já vimos o gráfico da função](funcoes.qmd#fx-frac1x) $f(x) = \frac{1}{x}$, e o limite com x tendendo à zero não existe.



## Aula 4 - Exemplos (parte 2)

### Exemplo 1

$$
\lim_{x \to 0} \frac{x}{x} =
\lim_{x \to 0} \frac{\cancel{x}}{\cancel{x}} = \lim_{x \to 0} \space 1 = 1
$$

Podemos cancelar o $x$ pois $x \neq 0$.

### Exemplo 2

$$
\lim_{x \to 0} \frac{x^2}{x^4} = 
\lim_{x \to 0} \frac{1}{x^2} = + \infty
$$

A intuição é: $x^2$ com $x$ tendendo a zero é um número muito pequeno, e $1$ dividido por um número muito pequeno é um número muito grande. Portanto, o limite é infinito positivo.

### Exemplo 3

$$
\lim_{x \to 0} \frac{x}{x^2} =
\lim_{x \to 0} \frac{1}{x} \Rightarrow \nexists \lim_{x \to 0} \frac{1}{x}
$$
Novamente:  [já vimos o gráfico da função](funcoes.qmd#fx-frac1x) $f(x) = \frac{1}{x}$, e o limite com x tendendo à zero não existe.

### Exemplo 4

$$ 
\lim_{x \to +\infty} x. \sin \frac{1}{x} =
$$
Para este exemplo, precisamos utilizar a **técnica de mudança de variável**.

Seja $u = \frac{1}{x}$ (estamos criando essa variável para substituir), então $x = \frac{1}{u}$ (apenas fizemos manipulação algébrica).

Se $x \to +\infty$ (ou seja, $x$ for muito grande), e $u = \frac{1}{x}$, então teremos 

$$
u = \frac{1}{\text{número muito grande positivo}} = \\
 \text{número muito pequeno e positivo} = 0^+
$$

então $u \to 0^+$.

Substituindo $x$ por $\frac{1}{u}$, temos:

$$
\lim_{u \to 0^+} \frac{1}{u} . \sin u =
$$
Esse é o caso do limite fundamental do cálculo $\lim_{x \to 0}\frac{\sin x}{x}$, que será explorado [em breve](lim-fundamental-senx-x.qmd).


## Aula 5 - P13) Calcule, caso existam, os limites abaixo:


### 1) Intuição

$$\lim_{x \to 1} \space x^2 = 1$$

### 2) Intuição

$$\lim_{x \to 1^+} x^3 + 2 = 3$$

### 3) Intuição

$$\lim_{x \to 1^+} 4x^5 - 7x^2 + 1 = -2$$

### 4) Intuição

$$\lim_{x \to 1} \frac{x^2 + 1}{x^3 + 2} = \frac{2}{3}$$

### 5') Intuição

$$\lim_{x \to 2} \frac{x^2 - 2}{x} = 1$$

### 5) Fatoração

$$
\lim_{x \to 0} \frac{x^2 - x}{x} 
= \lim_{x \to 0} \frac{x(x - 1)}{x} 
= \lim_{x \to 0} \frac{\cancel{x}(x - 1)}{\cancel{x}}
= \lim_{x \to 0} x - 1 = -1
$$

### 6') Intuição

$$\lim_{x \to 1} \frac{x^2 - 1}{x+1} = 0$$

### 6) Fatoração

$$
\lim_{x \to 1} \frac{x^2 - 1}{x-1}
=\lim_{x \to 1} \frac{x^2 - 1^2}{x-1}
$$

Aqui podemos fatorar: $a^2 - b^2 = (a+b)(a-b)$


$$
= \lim_{x \to 1} \frac{(x-1)(x+1)}{x-1}
= \lim_{x \to 1} \frac{\cancel{(x-1)}(x+1)}{\cancel{x-1}}
= \lim_{x \to 1} x + 1 = 2
$$

### 7') Intuição

$$
\lim_{x \to 2} \frac{\sqrt{x} - \sqrt{2}}{x + 2} 
=  0
$$

### 7'') Intuição

$$
\lim_{x \to 2} \frac{x-2}{x-2}
= \lim_{x \to 2} \frac{\cancel{x-2}}{\cancel{x-2}}
= \lim_{x \to 2} \space 1 = 1
$$


### 7) Racionalização, fatoração, intuição

Primeiro, precisamos utilizar a técnica de racionalização:

$$
\lim_{x \to 2} \frac{\sqrt{x} - \sqrt{2}}{x - 2}
= \lim_{x \to 2} \frac{(\sqrt{x} - \sqrt{2}) . \color{blue}{(\sqrt{x} + \sqrt{2})}}{(x - 2) . \color{blue}{(\sqrt{x} + \sqrt{2})}}
$$

Agora, podemos fatorar:

$$
= \lim_{x \to 2} \frac{(\sqrt{x})^2 - (\sqrt{2})^2}{(x - 2) . (\sqrt{x} + \sqrt{2})}
$$


$$
= \lim_{x \to 2} \frac{x - 2}{(x - 2) . (\sqrt{x} + \sqrt{2})}
= \lim_{x \to 2} \frac{\cancel{x - 2}}{\cancel{(x - 2)} . (\sqrt{x} + \sqrt{2})}
$$

Agora, podemos utilizar a intuição:
$$
= \lim_{x \to 2} \frac{1}{\sqrt{x} + \sqrt{2}}
= \frac{1}{\sqrt{2} + \sqrt{2}}
= \frac{1}{2\sqrt{2}}
$$



### 8) Continuidade

::: {.callout-warning}
O professor disse que é importante conhecer bem os gráficos das funções seno e cosseno, pois eles são muito importantes para o cálculo de limites.

Esses gráficos foram feitos na aula que abordou [Funções trigonométricas](funcoes-trig.qmd).

Com o gráfico, sabemos que este limite é 0.
:::

$$
\lim_{x \to 0} \space \sin x = 0
$$



### 9) Limites laterais

$$
\lim_{x \to 0} \space \frac{|x|}{x}
$$

$$
\lim_{x \to 0^+} \space \frac{+x}{x} 
= \lim_{x \to 0^+} \space 1 = 1
$$
$$
\lim_{x \to 0^-} \space \frac{-x}{x}
= \lim_{x \to 0^-} \space -1 = -1
$$

Os limites laterais existem, e são diferentes, então o limite não existe.

$$
\nexists \lim_{x \to 0} \space \frac{|x|}{x}
$$


### Exemplos: simplificação algébrica

Exemplo 1:

$$
\lim_{x \to 0} \frac{9x}{x}
= \lim_{x \to 0} \frac{9\cancel{x}}{\cancel{x}}
= \lim_{x \to 0} 9 = 9
$$

Exemplo 2:


$$
\lim_{x \to 0} \frac{x}{x^3}
= \lim_{x \to 0} \frac{\cancel{x}}{\cancel{x} . x . x} 
= \lim_{x \to 0} \frac{1}{x^2}
= \lim_{x \to 0} \frac{1}{\cancelto{pequeno}{x^2}}
= +\infty
$$


## Aula 6 - P14) Calcule, caso existam, os limites abaixo:

### 1) Intuição

$$
\lim_{x \to 1} \frac{3x + 1}{4x + 2}
= \lim_{x \to 1} \frac{\cancelto{4}{3x + 1}}{\cancelto{6}{4x + 2}}
= \frac{2}{3}
$$

### 2) Limites laterais


A intuição não basta:

$$
\lim_{x \to 0} \frac{1}{\sin x}
= \lim_{x \to 0} \frac{1}{\cancelto{0}{\sin x}}
$$
Vamos tentar explorar os limites laterais:


$$
\lim_{x \to 0+} \frac{1}{\sin x}
= \lim_{x \to 0+} \frac{1}{\cancelto{0^+}{\sin x}}
= +\infty
$$

$$
\lim_{x \to 0-} \frac{1}{\sin x}
= \lim_{x \to 0-} \frac{1}{\cancelto{0^-}{\sin x}}
= -\infty
$$
Os limites laterais são diferentes, então o limite não existe.

$$
\nexists \lim_{x \to 0} \frac{1}{\sin x}
$$

### 3) Fatoração

$$
\lim_{x \to 2} \frac{x^2 -5x +6}{x-2}
= \lim_{x \to 2} \frac{(x-2)(x-3)}{x-2}
$$
$$
= \lim_{x \to 2} \frac{\cancel{(x-2)}(x-3)}{\cancel{x-2}}
= \lim_{x \to 2} x-3 = -1
$$

### 4') Racionalização, fatoração

$$
\lim_{x \to 2} \frac{\sqrt{x} - \sqrt{2}}{x-2}
$$
Racionalização:

$$
= \lim_{x \to 2} \frac{\sqrt{x} - \sqrt{2}}{x-2} . \color{blue}{\frac{\sqrt{x} + \sqrt{2}}{\sqrt{x} + \sqrt{2}}}
$$

Fatoração: $a^2 - b^2 = (a+b)(a-b)$

$$
= \lim_{x \to 2} \frac{(\sqrt{x})^2 - (\sqrt{2})^2}{x-2} . \frac{1}{\sqrt{x} + \sqrt{2}}
$$

$$
= \lim_{x \to 2} \frac{\cancel{x - 2}}{\cancel{x-2}} . \frac{1}{\sqrt{x} + \sqrt{2}}
$$

Agora podemos usar a intuição:

$$
= \lim_{x \to 2} \frac{\cancelto{1}{1}}{\cancelto{\sqrt{2}}{\sqrt{x}} + \sqrt{2}} = \frac{1}{2\sqrt{2}}
$$



### 4) [Difícil] Racionalização, fatoração

$$
\lim_{x \to 2} \frac{\sqrt[3]{x} - \sqrt[3]{2}}{x-2}
$$

Podemos reescrever como:
$$
= \lim_{x \to 2} \frac{1}{x-2} \cdot \frac{\sqrt[3]{x} - \sqrt[3]{2}}{1}
$$
Lembrando que:  $a^3 - b^3 = (a-b)(a^2 + ab + b^2)$ 

Então: $\color{green}{a-b} = \color{blue}{\dfrac{a^3 - b^3}{a^2 + ab + b^2}}$ 

Neste caso, vamos considerar que $a = \sqrt[3]{x}$ e $b = \sqrt[3]{2}$, então: $$a-b = \color{green}{\sqrt[3]{x} - \sqrt[3]{2}}$$

Vamos substituir o $a-b$ (ou seja, $\color{green}{\sqrt[3]{x} - \sqrt[3]{2}}$) pelo $\color{blue}{\dfrac{a^3 - b^3}{a^2 + ab + b^2}}$:

$$
= \lim_{x \to 2} \frac{1}{x-2} \cdot \color{blue}{\frac{(\sqrt[3]{x})^3 - (\sqrt[3]{2})^3}{(\sqrt[3]{x})^2 + \sqrt[3]{x} \cdot \sqrt[3]{2} + (\sqrt[3]{2})^2}}
$$
$$
= \lim_{x \to 2} \frac{1}{\cancel{x-2}} \cdot \frac{\cancel{x - 2}}{(\sqrt[3]{x})^2 + \sqrt[3]{x} \cdot \sqrt[3]{2} + (\sqrt[3]{2})^2}
$$
$$
= \lim_{x \to 2} \frac{1}{(\sqrt[3]{x})^2 + \sqrt[3]{x} \cdot \sqrt[3]{2} + (\sqrt[3]{2})^2}
$$

$$
= \lim_{x \to 2} \frac{1}{\cancelto{(\sqrt[3]{2})^2}{(\sqrt[3]{x})^2} + \cancelto{(\sqrt[3]{2})^2}{\sqrt[3]{x} \cdot \sqrt[3]{2}} + \cancelto{(\sqrt[3]{2})^2}{(\sqrt[3]{2})^2}}
$$
$$
= \lim_{x \to 2} \frac{1}{\cancelto{3(\sqrt[3]{2})^2}{(\sqrt[3]{x})^2 + \sqrt[3]{x} \cdot \sqrt[3]{2} + (\sqrt[3]{2})^2}} 
= \frac{1}{3(\sqrt[3]{2})^2}
$$



### 5) Primeiro limite fundamental do cálculo


$$
\lim_{x \to 0}  x^3 . \frac{\sin x}{x} 
= \lim_{x \to 0}  x^3 . \color{blue}{\frac{\sin x}{x}}
$$

Neste caso, vamos utilizar o primeiro limite fundamental do cálculo:

$$
\lim_{x \to 0}  x^3 . 1
=\lim_{x \to 0}  \cancelto{0}{x^3} . 1
= 0
$$



### 6) Mudança de variável, primeiro limite fundamental do cálculo

$$
\lim_{x \to 0}  \frac{\sin 7x}{x}
$$

Vamos tentar chegar até o primeiro limite fundamental do cálculo.

Vamos multiplicar em cima e em baixo por 7:

$$
= \lim_{x \to 0}  \frac{\sin 7x}{x} \cdot \color{blue}{\frac{7}{7} }
$$
$$
= \lim_{x \to 0}  \frac{\sin 7x . 7}{7x}
$$
Vamos utilizar a técnica de mudança de variável. Seja $u = 7x$, então: quando $x \to 0$, $u = 7x \to 0$.

$$
= \lim_{u \to 0}  \frac{7 \cdot \sin u}{u}
$$

Agora podemos utilizar o limite fundamental do cálculo:

$$
= \lim_{u \to 0} 7 \cdot \cancelto{1}{\color{blue}{\frac{\sin u}{u}}} = 7
$$


### 7) Mudança de variável, primeiro limite fundamental do cálculo


$$
\lim_{x \to 5} \frac{\sin (x - 5)}{x - 5}
$$


Vamos tentar chegar até o primeiro limite fundamental do cálculo.

Para isso, vamos fazer uma mudança de variável: $u = x - 5$, então $u = x - 5$ ou $x = u + 5$.

**IMPORTANTE:** Se $x \to 5$, então $u = x - 5 \to 0$.

Substituindo $x$ por $u + 5$, temos:

$$
\lim_{u \to 0} \frac{\sin u}{u}
$$

Agora, podemos utilizar o primeiro limite fundamental do cálculo:

$$
\lim_{u \to 0} \frac{\sin u}{u} = 1
$$



### 8) Primeiro limite fundamental do cálculo


$$
\lim_{x \to 0} \frac{\tan x}{x}
$$

Vamos tentar chegar até o primeiro limite fundamental do cálculo.

Sabemos que $\tan x = \frac{\sin x}{\cos x}$, então:

$$
\lim_{x \to 0} \frac{\tan x}{x}
= \lim_{x \to 0} \frac{\frac{\sin x}{\cos x}}{x}
= \lim_{x \to 0} \frac{\frac{\sin x}{\cancelto{1}{\cos x}}}{x}
= \lim_{x \to 0} \frac{\sin x}{x} = 1
$$


### 9') Intuição

$$
\lim_{x \to 2} \frac{\sin (x^2 - 4x + 4)}{x + 2}
$$

$$
\lim_{x \to 2} \frac{{\sin (\cancelto{4}{x^2} - \cancelto{-8}{4x} + \cancelto{4}{4})}}{\cancelto{4}{x + 2}}
$$
$$
\lim_{x \to 2} \frac{\sin (\cancelto{0}{x^2 - 4x + 4)}}{\cancelto{4}{x + 2}}
$$

Sabemos que $\sin 0 = 0$, então:

$$
\lim_{x \to 2} \frac{\cancelto{0}{\sin (x^2 - 4x + 4)}}{\cancelto{4}{x + 2}} = 0
$$

### 9) [Difícil] Fatoração, mudança de variável,  limite fundamental do cálculo

$$
\lim_{x \to 2} \frac{\sin (x^2 - 4x + 4)}{x - 2}
$$

Como temos o seno, precisamos tentar chegar até o primeiro limite fundamental do cálculo.

De início, tentei fatorar o $x^2 - 4x + 4$, mas não adiantou para chegar no primeiro limite fundamental do cálculo.

Como o professor resolveu? Primeiro, ele multiplicou em cima e em baixo por $x^2 - 4x + 4$:

$$
\lim_{x \to 2} \frac{\sin (x^2 - 4x + 4)}{x - 2} \cdot \color{blue}{
\frac{x^2 - 4x + 4}{x^2 - 4x + 4}}
$$
Podemos reorganizar da seguinte forma:

$$
\lim_{x \to 2} \frac{\sin (x^2 - 4x + 4)}{x^2 - 4x + 4} \cdot {\frac{x^2 - 4x + 4}{x - 2}}
$$

Neste ponto, o professor separou em duas partes!

#### Parte 1: Mudança de variável, primeiro limite fundamental do cálculo

Primeiro, ele resolveu o limite:

$$\lim_{x \to 2} \frac{\sin (x^2 - 4x + 4)}{x^2 - 4x + 4}$$

Aqui podemos chegar no limite fundamental do cálculo fazendo uma mudança de variável:

$$\theta = x ^2 - 4x + 4$$

Então, como $x$ tende a 2, $\theta$ tende a 0: $\theta = 2 ^2 - 4\cdot2 + 4 \to 0$.

Podemos reescrever:

$$\lim_{x \to 0} \frac{\sin \theta}{\theta} = 1$$ 

#### Parte 2: Fatoração

Agora, vamos resolver a segunda parte:

$$
\lim_{x \to 2} \frac{x^2 - 4x + 4}{x - 2}
$$

Podemos fatorar:

$$
= \lim_{x \to 2} \frac{(x-2)\cdot(x-2)}{x - 2}
$$


$$
= \lim_{x \to 2} \frac{(x-2)\cdot\cancel{(x-2)}}{\cancel{x - 2}}
$$
$$
= \lim_{x \to 2} x - 2 = 0
$$

#### Parte 3

Agora, vamos multiplicar os resultados das duas partes:

$$
\lim_{x \to 2} \frac{\sin (x^2 - 4x + 4)}{x - 2} = 1 \cdot 0 = 0
$$

### 10) [Difícil] Primeiro limite fundamental do cálculo

$$
\lim_{x \to 0^-} \frac{1 - \cos x}{x^2}
$$

Temos o cosseno, mas podemos tentar chegar no primeiro limite fundamental do cálculo.

::: {.callout-important}
[Identidade trigonométrica fundamental](https://pt.wikipedia.org/wiki/Identidade_trigonom%C3%A9trica_fundamental) (*Pythagorean trigonometric identity*): 
$$sen^2 x + cos^2 x = 1$$

Então: 

$$sen^2 x = 1 - cos^2 x$$
:::


Lembrando que $a^2 - b^2 = (a+b)(a-b)$, e isso pode nos ajudar a chegar onde precisamos.

Vamos multiplicar em cima e em baixo por $1 + \cos x$:

$$
\lim_{x \to 0^-} \frac{1 - \cos x}{x^2} \cdot \color{blue}{\frac{1 + \cos x}{1 + \cos x}}
$$

$$
= \lim_{x \to 0^-} \frac{1^2 - \cos^2 x}{x^2 \cdot (1 + \cos x)}
$$

Lembrando que: $$sen^2 x = 1 - cos^2 x$$:


$$
= \lim_{x \to 0^-} \frac{\sin^2 x}{x^2 \cdot (1 + \cos x)}
$$

Para chegar no limite fundamental, podemos reescrever como:

$$
= \lim_{x \to 0^-} \frac{\sin^2 x}{x^2} \cdot \frac{1}{1 + \cos x}
$$


$$
= \lim_{x \to 0^-} (\frac{\sin x}{x})^2 \cdot \frac{1}{1 + \cos x}
$$

Agora sim encontramos o limite fundamental:

$$
= \lim_{x \to 0^-} (\cancelto{1}{\frac{\sin x}{x}})^2 \cdot \frac{1}{1 + \cancelto{1}{\cos x}}
$$

$$
= \lim_{x \to 0^-} \cancelto{1}{(\frac{\sin x}{x})^2} \cdot \frac{1}{\cancelto{2}{1 + \cos x}} = \frac{1}{2}
$$

### 11) [Difícil] Primeiro limite fundamental do cálculo


$$
\lim_{x \to 0^+} \frac{1 - \cos x}{x^2}
$$

A resposta é igual ao exercício anterior. Neste caso, os limites laterais são iguais.

### 12) Mudança de variável

$$
\lim_{x \to 2^+} \frac{1}{x-2}
$$
Neste caso, a intuição não basta (cai em indeterminação).

Vamos tentar fazer uma mudança de variável: $u = x - 2$.

Se $x \to 2^+$, então $u = x - 2 \to 0^+$.

Substituindo, temos:

$$
\lim_{u \to 0^+} \frac{1}{u}
$$

Neste caso, dividir 1 por um número muito pequeno e positivo é um número muito grande e positivo ($+ \infty$).


$$
\lim_{u \to 0^+} \frac{1}{u} = +\infty
$$


### 13) Mudança de variável

$$
\lim_{x \to 2^-} \frac{1}{x-2}
$$

Similar ao exercício anterior.

Neste caso, a intuição não basta (cai em indeterminação).

Vamos tentar fazer uma mudança de variável: $u = x - 2$.

Se $x \to 2^-$, então $u = x - 2 \to 0^-$.

Substituindo, temos:

$$
\lim_{u \to 0^-} \frac{1}{u}
$$

Neste caso, dividir 1 por um número muito pequeno e negativo é um número muito grande e negativo ($- \infty$).


$$
\lim_{u \to 0^-} \frac{1}{u} = -\infty
$$

### 12-13b) Mudança de variável

Esse não estava na lista.

$$
\lim_{x \to 2} \frac{1}{x-2}
$$

Nos exercícios anteriores, vimos que os limites laterais existem e são diferentes. Portanto:

$$
\nexists \lim_{x \to 2} \frac{1}{x-2}
$$

### 14) Intuição

$$
\lim_{x \to +\infty} x^6 + 7x + 2025
= \lim_{x \to +\infty} \cancelto{+\infty}{x^6} + \cancelto{+\infty}{7x} + 2025
= +\infty
$$


### Exemplo 1)

$$
\lim_{x \to +\infty} x-x
= \lim_{x \to +\infty} \cancelto{+\infty}{x} - \cancelto{-\infty}{x}
$$
Neste caso, vamos fazer uma simplificação algébrica:

$$
= \lim_{x \to +\infty} x - x
= \lim_{x \to +\infty} \cancel{x} - \cancel{x}
= \lim_{x \to +\infty} 0 
= 0
$$

### Exemplo 2)

$$
\lim_{x \to +\infty} 35x - x
= \lim_{x \to +\infty} 34x
= \lim_{x \to +\infty} \cancelto{+\infty}{34x}
= +\infty
$$

### Exemplo 3)

$$
\lim_{x \to +\infty} (x + 34) - x
= \lim_{x \to +\infty} x + 34 - x 
= \lim_{x \to +\infty} \cancel{x} + 34 - \cancel{x} 
= \lim_{x \to +\infty} 34 = 34
$$

### 15) Polinômios

$$
\lim_{x \to +\infty} x^6 - 7x + 2025
$$

Neste caso a intuição não basta:

$$
\lim_{x \to +\infty} \cancelto{+\infty}{x^6} \cancelto{-\infty}{-7x} + 2025
$$

Vamos usar as técnicas de polinômios: deixar em evidência a potência de maior grau. Isso pode ser usado quando houver um limite de polinômio com x tendendo à $+\infty$ ou $-\infty$.

$$
\lim_{x \to +\infty} x^6 .(1 - \frac{7x}{x^6} + \frac{2025}{x^6})
$$

$$
\lim_{x \to +\infty} x^6 .(1 - \frac{7}{x^5} + \frac{2025}{x^6})
$$
Intuição:
$$
\lim_{x \to +\infty} x^6 .(\cancelto{1}{1} - \cancelto{0}{\frac{7}{x^5}} + \cancelto{0}{\frac{2025}{x^6}})
$$
$$
\lim_{x \to +\infty} x^6
= \lim_{x \to +\infty} \cancelto{+\infty}{x^6} 
= +\infty
$$

### 15b) Polinômios

$$
\lim_{x \to -\infty} x^5 - x^4 + 2
= \lim_{x \to -\infty} \cancelto{-\infty}{x^5} - \cancelto{+\infty}{x^4} + \cancelto{2}{2}
$$
A intuição basta!

Vamos utilizar a técnica de polinômios: deixar em evidência a potência de maior grau.

$$
\lim_{x \to -\infty} x^5 - x^4 + 2
= \lim_{x \to -\infty} x^5 . (1 - \frac{x^4}{x^5} + \frac{2}{x^5})
= \lim_{x \to -\infty} x^5 . (1 - \frac{1}{x} + \frac{2}{x^5})
$$

Agora vamos usar a intuição:

$$
\lim_{x \to -\infty} x^5 . \cancelto{1}{(\cancelto{1}{1} - \cancelto{0}{\frac{1}{x}} + \cancelto{0}{\frac{2}{x^5}})}
$$

$$
\lim_{x \to -\infty} x^5 
= \lim_{x \to -\infty} \cancelto{-\infty}{x^5}
= -\infty
$$


### 16) Polinômios


$$
\lim_{x \to +\infty} \dfrac{3x^3 + 7x + 1}{4x^4 + 1}
$$

Vamos usar a técnica de polinômios: Simplificar o que dá - a maior potência em comum em cima e em baixo.

$$
\lim_{x \to +\infty} \dfrac{x^3.(3 + \frac{7x}{x^3} + \frac{1}{x^3})}{x^3. (4x + \frac{1}{x^3})}
$$

$$
\lim_{x \to +\infty} \dfrac{\cancel{x^3}.(3 + \frac{7x}{x^3} + \frac{1}{x^3})}{\cancel{x^3}. (4x + \frac{1}{x^3})}
$$
$$
\lim_{x \to +\infty} \dfrac{3 + \frac{7\cancel{x}}{x.x.\cancel{x}} + \frac{1}{x^3}}{4x + \frac{1}{x^3}}
$$

$$
\lim_{x \to +\infty} \dfrac{\cancelto{\space \space 3}{\cancelto{3}{3} + \cancelto{0}{\frac{7}{x^2}} + \cancelto{0}{\frac{1}{x^3}}}}{\cancelto{\space +\infty}{\cancelto{+\infty}{4x} + \cancelto{0}{\frac{1}{x^3}}}} = 0
$$
O limite é zero, pois se dividir um número finito (neste caso, o 3) por um número muito grande ($+\infty$), o resultado é zero.

### 17) Polinômios

$$
\lim_{x \to +\infty} \dfrac{2x^3 + 7}{4x^3 + 2x^2 + 1}
$$

Vamos usar a técnica de polinômios: Simplificar o que dá - a maior potência em comum em cima e em baixo.

$$
\lim_{x \to +\infty} \dfrac{x^3.(2 + \frac{7}{x^3})}{x^3. (4 + \frac{2}{x} + \frac{1}{x^3})}
$$ 

$$
= \lim_{x \to +\infty} \dfrac{\cancel{x^3}.(2 + \frac{7}{x^3})}{\cancel{x^3}. (4 + \frac{2}{x} + \frac{1}{x^3})}
$$

$$
= \lim_{x \to +\infty} \dfrac{2 + \dfrac{7}{x^3}}{4 + \dfrac{2}{x} + \dfrac{1}{x^3}}
$$

$$
= \lim_{x \to +\infty} \dfrac{2 + \cancelto{0}{\dfrac{7}{x^3}}}{4 + \cancelto{0}{\dfrac{2}{x}} + \cancelto{0}{\dfrac{1}{x^3}}}
\\ = \frac{2}{4} 
$$

### 18) Polinômios

$$
\lim_{x \to -\infty} \dfrac{2x + 1}{3x^3 + 7}
$$

$$
\lim_{x \to -\infty} \dfrac{x.(2 + \frac{1}{x})}{x.(3x^2 + \frac{7}{x})}
$$

$$
= \lim_{x \to -\infty} \dfrac{\cancel{x}.(2 + \frac{1}{x})}{\cancel{x}.(3x^2 + \frac{7}{x})}
$$

$$
= \lim_{x \to -\infty} \dfrac{2 + \frac{1}{x}}{3x^2 + \frac{7}{x}}
$$

$$
= \lim_{x \to -\infty} \dfrac{\cancelto{\space 2}{2 + \cancelto{0}{\frac{1}{x}}}}
{\cancelto{+\infty}{\cancelto{+\infty}{3x^2} + \cancelto{0}{\frac{7}{x}}}} = 0
$$

