---
title: "Limites"
subtitle: "Lista 1"
---


## 1. Calcule os limites abaixo:

### 1. Primeiro limite fundamental, racionalização, fatoração

> Ele resolveu em sala (na aula 7). Mas tive que sair para uma chamada e perdi. A forma a seguir é como eu tentei resolver, mas não sei se está igual à resolução do professor.

$$
\lim_{x \to 0} \frac{\sqrt{x^2+25}-5}{x \cdot \sin x}
$$

Temos $\sin x$, então podemos usar o primeiro limite fundamental do cálculo. Mas ainda não está na forma que precisamos.

Vamos tentar destruir a raíz quadrada primeiro!

Lembrando da técnica de fatoração de diferença de quadrados:
$$
(a^2 - b^2) = (a-b)(a+b)
$$

Vamos considerar que:

  - $a = \sqrt{x^2 + 25}$
  - $b = 5$

Podemos multiplicar em cima e em baixo por $a + b$, ou seja, $\sqrt{x^2 + 25} + 5$.

$$
= \lim_{x \to 0} \frac{\sqrt{x^2+25}-5}{x \cdot \sin x} \color{red}{\cdot \frac{\sqrt{x^2+25}+5}{\sqrt{x^2+25}+5}}
$$


Vamos fazer usar a técnica de fatoração de diferença de quadrados:

$$
= \lim_{x \to 0} \frac{(\sqrt{x^2+25})^2 - 5^2}{x \cdot \sin x} \cdot \frac{1}{\sqrt{x^2+25}+5}
$$

Vamos chamar $\sqrt{x^2+25}+5$ de $c$. Assim vai ficar mais fácil de entender.


$$
= \lim_{x \to 0} \frac{x^2+ 25 - 25}{x \cdot \sin x} \cdot \frac{1}{\color{blue}{c}}
$$


$$
= \lim_{x \to 0} \frac{x^2}{x \cdot \sin x} \cdot \frac{1}{\color{blue}{c}}
$$


$$
= \lim_{x \to 0} \frac{x \cdot \cancel{x}}{\cancel{x} \cdot \sin x} \cdot \frac{1}{\color{blue}{c}}
$$

$$
= \lim_{x \to 0} \frac{x}{\sin x} \cdot \frac{1}{\color{blue}{c}}
$$

Agora vamos dividir em cima e em baixo por $x$ (assim ficaremos mais perto do primeiro limite fundamental):

$$
= \lim_{x \to 0} \frac{\frac{x}{\color{red}{x}}}{\frac{ \sin x}{\color{red}{x}}}\cdot \frac{1}{\color{blue}{c}}
$$
Agora podemos usar o primeiro limite fundamental:

$$
= \lim_{x \to 0} \frac{1}{\frac{\sin x}{x}} \cdot \frac{1}{\color{blue}{c}}
$$


$$
= \lim_{x \to 0} \frac{1}{\cancelto{1}{\frac{\sin x}{x}}} \cdot \frac{1}{\color{blue}{c}}
$$
$$
= \lim_{x \to 0} \frac{1}{\color{blue}{c}}
$$

Agora vamos substituir o $c$:

$$
= \lim_{x \to 0} \frac{1}{\color{blue}{\sqrt{x^2+25}+5}}
$$

Podemos usar a intuição:

$$
= \lim_{x \to 0} \frac{1}{\sqrt{\cancelto{0}{x^2}+25}+5}
$$

$$
= \frac{1}{\sqrt{25}+5} =  \frac{1}{5+5} = \frac{1}{10}
$$


### 2. Racionalização, fatoração

$$
\lim_{x \to 1} \frac{\sqrt{x}-1}{\sqrt{2x+3}-\sqrt{5}}
$$

Com $x \to 1$, temos que $\sqrt{2x+3}-\sqrt{5} \to 0$. Não podemos substituir diretamente, pois dá indeterminação (neste caso, dividir por zero). Além disso, com $x \to 1$, temos $\sqrt{x-1} \to 0$, e não podemos substituir diretamente.

Vamos precisar destruir raízes.

Lembrando que:
$$
(a^2 - b^2) = (a-b)(a+b)
$$

Vamos multiplicar em cima e em baixo por $\sqrt{2x+3}+\sqrt{5}$ e $\sqrt{x}+1$.

$$
= \lim_{x \to 1} \frac{\sqrt{x}-1}{\sqrt{2x+3}-\sqrt{5}} \color{blue}{\cdot \frac{\sqrt{2x+3}+\sqrt{5}}{\sqrt{2x+3}+\sqrt{5}}}\color{red}{\cdot \frac{\sqrt{x} + 1}{\sqrt{x} + 1}}
$$
Agora podemos fatorar a diferença de quadrados:


$$
= \lim_{x \to 1} \frac{(\sqrt{x})^2 - 1^2}{(\sqrt{2x+3})^2-(\sqrt{5})^2}
\cdot \frac{\sqrt{2x+3}+\sqrt{5}}{\sqrt{x} + 1}
$$
$$
= \lim_{x \to 1} \frac{(x - 1)}{(2x+3-5)}
\cdot \frac{(\sqrt{2x+3}+\sqrt{5})}{(\sqrt{x} + 1)}
$$
$$
= \lim_{x \to 1} \frac{(x - 1)}{(2x-2)}
\cdot \frac{(\sqrt{2x+3}+\sqrt{5})}{(\sqrt{x} + 1)}
$$

Fatorar:

$$
= \lim_{x \to 1} \frac{\cancel{(x - 1)}}{2\cancel{\cdot(x-1)}}
\cdot \frac{(\sqrt{2x+3}+\sqrt{5})}{(\sqrt{x} + 1)}
$$
$$
= \lim_{x \to 1} \frac{1}{2}
\cdot \frac{(\sqrt{2x+3}+\sqrt{5})}{(\sqrt{x} + 1)}
$$

Vamos tentar a intuição (substituição direta):

$$
= \lim_{x \to 1} \frac{1}{2}
\cdot 
\frac{
\cancelto{\sqrt{5}}{(\sqrt{2x+3})}+\sqrt{5}
}{
(\cancelto{1}{\sqrt{x}} + 1)
}
$$

$$
= \frac{1}{2}
\cdot 
\frac{
\cancel{2} \sqrt{5}
}{
\cancel{2}
}
= \frac{\sqrt{5}}{2}
$$


### 3. Fatoração, Limites laterais


$$
\lim_{x \to 1} \frac{2x+1}{x^2+2x-3}
$$

Não podemos substituir diretamente, pois dá indeterminação: $1^2 + 2*1 - 3 = 0$ (neste caso, dividir por zero).

Vamos fatorar o denominador:

$$
= \lim_{x \to 1} \frac{2x+1}{(x + 3) \cdot (x - 1)}
$$

Como $x \to 1$ e temos um $x - 1$ no denominador, isso causa uma indeterminação (neste caso, dividir por zero, pois o $x - 1$ está multiplicando).

Vamos utilizar a técnica dos limites laterais.

Vamos fazer o limite lateral à esquerda:

$$
= \lim_{x \to 1^-} \frac{2x+1}{(x + 3) \cdot (x - 1)}
$$
$$
= \lim_{x \to 1^-} \frac{\cancelto{3}{2x+1}}{\cancelto{4}{(x + 3)} \cdot \cancelto{0^-}{(x - 1)}}
= - \infty
$$

Explicação acima: O denominador está tendendo para o zero negativo, e o numerador está tendendo para 3.  Então, o limite lateral à esquerda é $-\infty$.

Agora vamos fazer o limite lateral à direita:



$$
\lim_{x \to 1^+} \frac{2x+1}{(x + 3) \cdot (x - 1)}
$$
$$
= \lim_{x \to 1^+} \frac{\cancelto{3}{2x+1}}{\cancelto{4}{(x + 3)} \cdot \cancelto{0^+}{(x - 1)}}
= + \infty
$$

Explicação acima: O denominador está tendendo para o zero positivo, e o numerador está tendendo para 3.  Então, o limite lateral à esquerda é $+\infty$.

Como os limites laterais são diferentes, o limite não existe.

$$
\nexists \lim_{x \to 1} \frac{2x+1}{x^2+2x-3}
$$


### 4. Mudança de variável, fatoração

$$
\lim_{x \to 1} \frac{\sqrt[4]{x}-1}{\sqrt[3]{x}-1}
$$

Não podemos substituir diretamente, pois dá indeterminação: $\frac{0}{0}$.


Mudança de variável: $x = y^{12}$

$$
= \lim_{y \to 1} \frac{y^3 - 1}{y ^4 - 1}
$$

$$
= \lim_{y \to 1} \frac{(y - 1) (y ^2 + y + 1)}{(y-1) (y+1) (y ^2 + 1)}
$$

$$
= \lim_{y \to 1} \frac{\cancel{(y - 1)} (y ^2 + y + 1)}{\cancel{(y-1)} (y+1) (y ^2 + 1)}
$$

Usando a intuição:

$$
= \lim_{y \to 1} \frac{\cancelto{3}{(y ^2 + y + 1)}}{\cancelto{2}{(y+1)} \cancelto{2}{(y ^2 + 1)}} = \frac{3}{4}
$$


### 5. Limite lateral (módulo)

$$
\lim_{x \to 1^+} \frac{|x-1|}{x-1}
$$

Como temos módulo, poderíamos fazer os limites laterais. Porém, neste caso, o $x$ está tendendo à direita, ou seja, $x \to 1^+$ (então já é um limite lateral).


Considerar que, com $x \to 1^+$, então $|x-1| > 0$. Então podemos substituir o $|x-1|$ por $x-1$.

$$
= \lim_{x \to 1^+} \frac{x-1}{x-1} 
$$

$$
= \lim_{x \to 1^+} \frac{\cancel{x-1}}{\cancel{x-1}}=1 
$$

### 6. Fatoração

$$
\lim_{x \to 2^-} \frac{x^2-2x}{x^2-4x+4}
$$
Não podemos substituir diretamente, pois dá indeterminação: $2^2 - 4*2 + 4 = 4 - 8 + 4 = 0$.

Vamos fatorar o numerador e o denominador:

$$
= \lim_{x \to 2^-} \frac{x \cdot (x-2)}{(x-2)\cdot(x - 2)}
$$

$$
= \lim_{x \to 2^-} \frac{x \cdot \cancel{(x-2)}}{(x-2)\cdot \cancel{(x - 2)}}
$$

$$
= \lim_{x \to 2^-} \frac{x}{(x-2)}
$$

Agora podemos usar a intuição:


$$
= \lim_{x \to 2^-} \frac{\cancelto{2}{x}}{\cancelto{0^-}{(x-2)}} = - \infty
$$


### 7. Primeiro limite fundamental, substituição de variável, Produto de limites

$$
\lim_{x \to 3} \frac{\sin(x^2-5x+6)}{x-3}
$$

Temos a função seno, isso indica que podemos usar o limite fundamental.

Vamos fatorar!

$$
= \lim_{x \to 3} \frac{\sin((x - 2)(x - 3))}{x-3}
$$

Vamos multiplicar em cima e em baixo por $(x - 2)$:

$$
= \lim_{x \to 3} \frac{\sin((x - 2)(x - 3))}{x-3} \cdot \color{red}{\frac{(x - 2)}{(x - 2)}}
$$

Vamos reorganizar para ficar mais claro:

$$
= \lim_{x \to 3} \frac{\sin((x - 2)(x - 3))}{(x - 2)(x-3)} \cdot \frac{(x - 2)}{1}
$$


Existe uma propriedade que diz que o limite de um produto é o produto dos limites, caso os limites existam. 

$$
lim_{x \to a} [f(x) \cdot g(x)] = \left( \lim_{x \to a} f(x) \right) \cdot \left( \lim_{x \to a} g(x) \right)
$$
Podemos então separar os limites:



#### Primeiro limite fundamental

$$
= \lim_{x \to 3} \frac{\sin((x - 2)(x - 3))}{(x - 2)(x-3)} 
$$

Mudança de variável: $u = (x - 3).(x-2)$

Quando $x \to 3$, temos que $u \to 0$.

Precisamos reescrever tudo em função de $u$:



$$
= \lim_{u \to 0} \frac{\sin u}{u} = 1
$$

#### Substituição direta

$$
\lim_{x \to 3} (x - 2) = 1
$$

#### Resposta final

$$
= \lim_{x \to 3} \cancelto{1}{\frac{\sin((x - 2)(x - 3))}{(x - 2)(x-3)}} \cdot \cancelto{1}{(x - 2)} = 1
$$


### 8. Primeiro limite fundamental, substituição de variável, fatoração

$$
\lim_{x \to 4} \frac{\tan(x-4)}{x^2-16}
$$

A tangente pode ser transformada na função seno, e aí podemos utilizar o limite fundamental.

Lembrando que:
$$
\tan x = \frac{\sin x}{\cos x}
$$

Para ficar mais fácil, podemos reescrever:

$$
= \lim_{x \to 4} \frac{\tan(x-4)}{1} \cdot  \frac{1}{x^2-16}
$$

Podemos substituir a tangente por seno e cosseno, e fatorar o denominador:

$$
= \lim_{x \to 4} \frac{\sin(x-4)}{\cos(x-4)} \cdot  \frac{1}{x^2-16}
$$

Vamos fatorar o $x^2 - 16$:

$$
= \lim_{x \to 4} \frac{\sin(x-4)}{\cos(x-4)} \cdot  \frac{1}{(x - 4)(x + 4)}
$$
Podemos reescrever para facilitar encontrar o limite fundamental:


$$
= \lim_{x \to 4} \frac{\sin(x-4)}{(x - 4)} \cdot  \frac{1}{\cos(x-4) \cdot (x + 4)}
$$

O limite de produto é o produto dos limites, caso os limites existam.

Vamos separar em duas partes!

#### Parte 1 - Limite fundamental

$$
\lim_{x \to 4} \frac{\sin(x-4)}{(x - 4)} 
$$


Vamos fazer a substituição de variável $u = x - 4$:

Quando $x \to 4$, temos que $u \to 0$.


Podemos usar o primeiro limite fundamental:

$$
= \lim_{u \to 0} \frac{\sin u}{u} = 1
$$

#### Parte 2 - Substituição direta

$$
= \lim_{x \to 4}  \frac{1}{\cos(x-4) \cdot (x + 4)}
$$
$$
= \lim_{x \to 4}  \frac{1}{\cancelto{1}{\cos(x-4)} \cdot \cancelto{8}{(x + 4)}} = \frac{1}{8}
$$
#### Resposta final

$$
= \lim_{x \to 4} \cancelto{1}{\frac{\sin(x-4)}{(x - 4)}} \cdot \cancelto{\frac{1}{8}}{\frac{1}{\cos(x-4) \cdot (x + 4)}} = \frac{1}{8}
$$

### 9. TO DO
$$
\lim_{x \to 0} \frac{\sin(\sin x)}{3x}
$$

### 10. Polinômios

$$
\lim_{x \to -\infty} \frac{8x^2+1}{3x^3+8x+2}
$$

$$
= \lim_{x \to -\infty} \frac{x^2 \cdot (8 +\frac{1}{x^2})}{x^2 \cdot (3x+\frac{8}{x}+\frac{2}{x^2})}
$$


$$
= \lim_{x \to -\infty} \frac{\cancel{x^2} \cdot (8 +\frac{1}{x^2})}{\cancel{x^2} \cdot (3x+\frac{8}{x}+\frac{2}{x^2})}
$$


$$
= \lim_{x \to -\infty} \frac{\cancel{x^2} \cdot (8 +\frac{1}{x^2})}{\cancel{x^2} \cdot (3x+\frac{8}{x}+\frac{2}{x^2})}
$$

$$
= \lim_{x \to -\infty} \frac{8 + \cancelto{0^-}{\frac{1}{x^2}}}{ \cancelto{-\infty}{3x}+\cancelto{0^-}{\frac{8}{x}}+
\cancelto{0^-}{\frac{2}{x^2}}} = 0
$$


### 11. Racionalização, fatoração

$$
\lim_{x \to +\infty} x-\sqrt{x^2+3x}
$$

Precisamos destruir as raízes.

Lembrando que:
$(a−b)(a+b)=a^2−b^2$

Sendo: 

- $a=x$

- $b=\sqrt{x^2+3x}$



$$
=\lim_{x \to +\infty} x-\sqrt{x^2+3x} \color{red}{\cdot \frac{x+\sqrt{x^2+3x}}{x+\sqrt{x^2+3x}}}
$$
$$
=\lim_{x \to +\infty} x^2 - (\sqrt{x^2+3x})^2 \cdot \frac{1}{x+\sqrt{x^2+3x}}
$$
$$
=\lim_{x \to +\infty} \cancel{x^2} - (\cancel{x^2} + 3x) \cdot \frac{1}{x+\sqrt{x^2+3x}}
$$


$$
=\lim_{x \to +\infty}  \frac{-3x }{x+\sqrt{x^2+3x}}
$$

Vamos tentar deixar o $x$ do denominador em evidência, assim podemos cancelar.

> O Julio me ajudou nessa parte, estava com dificuldade. Mas é álgebra, e não cálculo.


Para isso, precisamos "tirar" o $x$ da raíz quadrada (que está no denominador).


$$
=\lim_{x \to +\infty}  \frac{x \cdot (-3)}{x+\sqrt{x^2\cdot(1 + \frac{3}{x})}}
$$
$$
=\lim_{x \to +\infty}  \frac{x \cdot (-3)}{x+ x \cdot \sqrt{1 + \frac{3}{x}}}
$$

$$
=\lim_{x \to +\infty}  \frac{x \cdot (-3)}{x \cdot (1 + \sqrt{1 + \frac{3}{x})}}
$$
$$
=\lim_{x \to +\infty}  \frac{\cancel{x} \cdot (-3)}{\cancel{x} \cdot (1 + \sqrt{1 + \frac{3}{x})}}
$$

Vamos utilizar a intuição:


$$
=\lim_{x \to +\infty}  \frac{ (-3)}{(1 + \sqrt{1 + \cancelto{0^+}{\frac{3}{x})}}} = \frac{-3}{2}
$$


### 12. TO DO
$$
\lim_{x \to 0} \frac{8x+\tan x}{7x-\tan x}
$$

### 13. TO DO
$$
\lim_{x \to +\infty} \frac{x}{\left(x^2+4\right)^{3/2}}
$$

### 14. TO DO
$$
\lim_{x \to +\infty} \frac{x+\sqrt{x+3}}{2x-1}
$$

### 15. Racionalização
$$
\lim_{x \to +\infty} \left(\sqrt{x+1}-\sqrt{x}\right)
$$

Lembrando de como trabalhar com a diferença de quadrados:
$$
a^2 - b^2 = (a-b)(a+b)
$$


Considerando :

  - $a = \sqrt{x+1}$

  - $b = \sqrt{x}$

$$
\lim_{x \to +\infty} \left(\sqrt{x+1}-\sqrt{x}\right) \color{red}{\cdot \frac{(\sqrt{x+1}+\sqrt{x})}{(\sqrt{x+1}+\sqrt{x})}}
$$
$$
= \lim_{x \to +\infty} \frac{(\sqrt{x+1})^2 - (\sqrt{x})^2}{\sqrt{x+1}+\sqrt{x}}
$$
Podemos tirar da raíz quadrada:
$$
= \lim_{x \to +\infty} \frac{(x+1) - x}{\sqrt{x+1}+\sqrt{x}}
$$

$$
= \lim_{x \to +\infty} \frac{\cancel{x}+1 - \cancel{x}}{\sqrt{x+1}+\sqrt{x}}
$$

$$
= \lim_{x \to +\infty} \frac{1}{\sqrt{x+1}+\sqrt{x}}
$$

Podemos usar a intuição:


$$
= \lim_{x \to +\infty} \frac{1}{\cancelto{+\infty}{\sqrt{x+1}+\sqrt{x}}} = 0
$$


### 16. Intuição

$$
\lim_{x \to 6^-} \frac{1}{x-6}
$$

$$
= \lim_{x \to 6^-} \frac{1}{\cancelto{0^-}{x-6}} = -\infty
$$


### 17. Primeiro limite fundamental, fatoração, substituição de variável, produto de limites

$$
\lim_{x \to 7} \frac{\sin(x^2-49)}{x-7}
$$


- Tem a função seno! Significa que precisamos usar o primeiro limite fundamental do cálculo. 

- Como chegar nisso? Dica do prof: multiplicar em cima e em baixo por $x^2-49$.

$$
= \lim_{x \to 7} \frac{\sin(x^2-49)}{x-7} \color{red}{ \cdot \frac{x^2-49}{x^2-49}}
$$

Podemos reorganizar: 

$$
= \lim_{x \to 7} \frac{\sin(x^2-49)}{x^2-49}  \cdot \frac{x^2-49}{x-7}
$$
Precisamos fazer uma mudança de variável (pois no primeiro limite fundamental o x tende à 0, mas neste caso o x está tendendo à 7).


Vamos fatorar o $x^2 - 49$:

$$
= \lim_{x \to 7} \frac{\sin((x-7)(x+7))}{(x-7)(x+7)}  \cdot \frac{(x-7)(x+7)}{x-7}
$$
E simplificar:

$$
= \lim_{x \to 7} \frac{\sin((x-7)(x+7))}{(x-7)(x+7)}  \cdot \frac{(x+7)\cancel{(x-7)}}{\cancel{x-7}}
$$
$$
= \lim_{x \to 7} \frac{\sin((x-7)(x+7))}{(x-7)(x+7)}  \cdot (x+7)
$$



Existe uma propriedade que diz que o limite de um produto é o produto dos limites, caso os limites existam. 

$$
lim_{x \to a} [f(x) \cdot g(x)] = \left( \lim_{x \to a} f(x) \right) \cdot \left( \lim_{x \to a} g(x) \right)
$$

Ou seja:



$$
=\lim_{x \to 7} \frac{\sin((x-7)(x+7))}{(x-7)(x+7)}  \cdot (x+7)
$$
$$
= \left[ \lim_{x \to 7} \frac{\sin((x-7)(x+7))}{(x-7)(x+7)} \right] \cdot \left[ \lim_{x \to 7} (x+7) \right]
$$


Vou calcular cada limite separadamente!

#### Parte 1 - Limite fundamental

$$
= \lim_{x \to 7} \frac{\sin((x-7)(x+7))}{(x-7)(x+7)}
$$

Agora, vamos fazer a mudança de variável.

$$u = (x -7)(x+7)$$

Quando $x \to 7$: 

- $u = (x-7)(x+7) = (7 - 7)(7+7) = 0 \cdot 14 = 0$. 

- Então $u \to 0$ quando $x \to 7$. 

Para substituir o $x$ por $u$, precisamos expressar $x$ em função de $u$.


$$
= \lim_{u \to 0} \frac{\sin u}{u}  = 1
$$

#### Parte 2 - Substituição direta

$$
= \lim_{x \to 7} (x+7) = 14
$$

#### Resposta final

$$
= \lim_{x \to 7} \cancelto{1}{\frac{\sin((x-7)(x+7))}{(x-7)(x+7)}} \cdot \cancelto{14}{(x+7)} = 14
$$


### 18. TO DO - Derivada

$$
\lim_{x \to 4} \frac{\tan x - \tan 4}{\sin x - \sin 4}
$$

Fazer por derivada.  Para chegar no formato, vamos dividir em cima e em baixo por $x - 4$.



### 19. Primeiro limite fundamental + Teorema da função limitada

Exercício resolvido em sala de aula!



$$
\lim_{x \to 0} \frac{x^2 \cdot \sin\frac{1}{x}}{\sin x}
$$


Vamos tentar chegar até o primeiro limite fundamental do cálculo: $\lim_{x \to 0} \frac{\sin x}{x} = 1$.


Vamos dividir a parte de cima e de baixo por $x$:

$$
= \lim_{x \to 0} \frac{\frac{x^2 \cdot \sin\frac{1}{x}}{x}}{\frac{\sin x}{x}}
$$

Encontramos o limite fundamental!

$$
= \lim_{x \to 0} \frac{x \cdot \sin\frac{1}{x}}{\cancelto{1}{\frac{\sin x}{x}}}
$$

$$
= \lim_{x \to 0} x \cdot \sin\frac{1}{x}
$$

$\sin \frac{1}{x}$ é limitada pois $|\sin \frac{1}{x}| \leq 1, \forall x \neq 0$.


$$
= \lim_{x \to 0} \cancelto{0}{x} \cdot \sin\frac{1}{x}
$$

::: {.callout-important}
Como $\lim_{x \to 0} x = 0$ e $g(x) = \sin \frac{1}{x}$ é limitada, pois $|\sin \frac{1}{x}| \leq 1, \forall x \neq 0$,
logo pelo teorema da função limitada (**T.F.L.**), o limite acima existe e vale zero.
:::

$$
= \lim_{x \to 0} x \cdot \sin\frac{1}{x} = 0
$$

### 20. TO DO

$$
\lim_{x \to 0} \frac{1-\cos x}{x^2}
$$

### 21. TO DO
$$
\lim_{x \to 0} \frac{e^{x^3}-1}{\sin 3x}
$$

### 22. TO DO - FAZER

$$
\lim_{x \to 1} \left(\frac{1}{x-1}-\frac{3}{1-x^3}\right)
$$

> tirei foto da resolução 17/04/2025.

### 23. TO DO - FAZER

$$
\lim_{x \to \frac{\pi}{2}} \frac{\cos x}{x-\frac{\pi}{2}}
$$

Não podemos fazer a substituição direta, pois dá indeterminação ($x- \frac{\pi}{2} = 0$).

Temos o $\cos x$, então podemos tentar usar o primeiro limite fundamental.

Fazer uma mudança de variável. Precisamos que o limite esteja com $x \to 0$.


$$u = x - \frac{\pi}{2}$$

Quando $x \to \frac{\pi}{2}$, $u =  \frac{\pi}{2} - \frac{\pi}{2} = 0$


$x = u + \frac{\pi}{2}$


$$
= \lim_{u \to 0} \frac{\cos  (u + \frac{\pi}{2})}{u}
$$

> TO DO: MELHORAR AS EXPLICAÇÕES DOS PASSOS AQUI


$$\cos (a) = \sin  (a + \frac{\pi}{2})$$

Substituindo:

$$
= \lim_{u \to 0} \frac{\sin  (u + \frac{\pi}{2}+ \frac{\pi}{2})}{u} \\
= \lim_{u \to 0} \frac{\sin  (u + \pi)}{u} 
$$

$$
\sin(u + \pi) = -1 . \sin u
$$


Usando o primeiro limite fundamental:
$$
= \lim_{u \to 0} -1 \cdot \cancelto{1}{\frac{\sin u}{u}} = -1
$$


### 24. TO DO

$$
\lim_{x \to +\infty} \frac{3x^5+2x-9}{\sqrt{x^6+x+1}}
$$

### 25. TO DO 
$$
\lim_{x \to 2} \frac{1}{x^2-5x+6}
$$




### 26.  Fatoração

$$
\lim_{x \to -1} \frac{(x+1)^2}{x^3+1}
$$

Podemos entender o denominador como uma soma de cubos: $x^3+1 = x^3 + 1^3$.

Lembrando que:
$$a^3 + b^3 = (a + b)(a^2 - ab + b^2)$$

Substituindo, temos:

$$
\lim_{x \to -1} \frac{(x+1)\cdot(x+1) }{(x + 1) \cdot (x^2 - x + 1)}
$$

$$
\lim_{x \to -1} \frac{\cancel{(x+1)}\cdot(x+1) }{\cancel{(x + 1)} \cdot (x^2 - x + 1)}
$$
$$
\lim_{x \to -1} \frac{(x+1)}{(x^2 - x + 1)}
$$

Podemos fazer a substituição direta (intuição):


$$
\lim_{x \to -1} \frac{\cancelto{0}{(x+1)}}{
\cancelto{3}{(x^2 - x + 1)}} = 0
$$


### 27. Segundo limite fundamental, mudança de variável

$$
\lim_{x \to +\infty} \left(1+\frac{7}{x}\right)^x
$$

Vamos utilizar o segundo limite fundamental:

$$
e = \lim_{x \to +\infty}  \left(1 + \frac{1}{x}\right)^x
$$

Vamos fazer uma mudança de variável. Seja:

$$
 \frac{7}{x} = \frac{1}{u} \rightarrow x = 7u
$$

Quando $x \to +\infty$, $u \to +\infty$.

$$
= \lim_{u \to +\infty} \left(1+\frac{1}{u}\right)^{7u}
$$

Manipulação de expoentes:


$$
= \lim_{u \to +\infty} \left[\left(1+\frac{1}{u}\right)^{u}\right]^7
$$

Utilizando o segundo limite fundamental:

$$
= \lim_{u \to +\infty} \left[\cancelto{\space e}{\left(1+\frac{1}{u}\right)^{u}}\right]^7 = e^7
$$

### 28. TO DO
$$
\lim_{x \to 0} \cos \frac{1}{x} \cdot{\sin(x^2)}
$$

### 29. TO DO
$$
\lim_{x \to +\infty} \frac{3x^5+2x-8}{\sqrt{x^2+2}}
$$

### 30. Limites laterais
$$
\lim_{x \to 2} \frac{1}{x-2}
$$

Nesse caso, não podemos fazer a substituição direta, pois dá indeterminação: $1/(2-2) = 1/0$.

Vamos fazer os limites laterais.

$$
=\lim_{x \to 2^-} \frac{1}{\cancelto{0^-}{x-2}} = -\infty
$$
$$
=\lim_{x \to 2^+} \frac{1}{\cancelto{0^+}{x-2}} = +\infty
$$
Como os limites laterais são diferentes, o limite não existe.

$$
\nexists \lim_{x \to 2} \frac{1}{x-2}
$$

### 31. Intuição
$$
\lim_{x \to 5^+} \frac{1}{x-5}
$$

$$
=\lim_{x \to 5^+} \frac{1}{\cancelto{0^+}{x-5}} = +\infty
$$

### 32. TO DO - Polinômios
$$
\lim_{x \to +\infty} \frac{3x^4-7x+2}{4x^3+7x+4}
$$

$$
=\lim_{x \to +\infty} \frac{x^3\cdot(3x - 7/x^2 + 2/x^3)}
{x^3 \cdot (4 + 7/x^2 + 4/x^3)}
$$


$$
=\lim_{x \to +\infty} \frac{\cancel{x^3} \cdot(3x - 7/x^2 + 2/x^3)}
{\cancel{x^3} \cdot (4 + 7/x^2 + 4/x^3)}
$$

> Continuar

