---
title: "Reta tangente"
---

```{r}
source("R/funcoes-plot.R")
```

## Lembremos

- $m = \tan \theta = f'(x_0)$


$$
(x, y) \in r \Leftrightarrow m = \frac{y - y_0}{x - x_0}
$$
$$
m(x - x_0) = y - y_0
$$
$$
y = m(x - x_0) + y_0 
$$

::: {.callout-note}
## Retas paralelas

Duas retas ($r$ e $s$) são paralelas se e somente se $m_r = m_s$ (o coeficiente angular das retas é igual).

$$
r // s \Leftrightarrow m_r = m_s
$$

:::

## P.46

**Mostre que não existe nenhuma reta tangente ao gráfico de ...**

$$
f(x) = \sin^{2025} x + 8x^{2025} + e^{x^3 + 1}  + 2005
$$

**...com $0 < x < \frac{\pi}{2}$ que seja paralela à reta $y = -x + 77$.**

- Etapa 1: encontrar o coeficiente angular ($m$) da reta $y = -x + 77$.

$m = -1$

Segundo o enunciado:

$$
\nexists \space x_0 \text{   tal que   } f'(x) = -1
$$

- Etapa 2: derivar a função $f(x)$.

$$
f(x) = \sin^{2025} x + 8x^{2025} + e^{x^3 + 1}  + 2005
$$

Vamos separar a função $f(x)$ em funções menores, para facilitar para derivar.

$$
g(x) = \sin^{2025} x \rightarrow g'(x) = 2025 \cdot (\sin^{2024} x) \cdot \cos x
$$

$$
h(x) = 8x^{2025} \rightarrow h'(x) = 8 \cdot 2025 \cdot x^{2024}
$$

$$
j(x) = e^{x^3 + 1} \rightarrow j'(x) = 3x^2 \cdot e^{x^3 + 1} 
$$

Com $0 < x < \frac{\pi}{2}$, todo $f'(x)$ sempre será positivo.

Logo: $f'(x_0) \geq 0, \forall x_0 \in D_f$.

Portanto: 

$$
\nexists \space x_0 \text{   para   } f'(x_0) = -1
$$


## P.47

**Mostre que existe uma única reta tangente ao gráfico de $f(x) = \ln(1 + x^2)$ que seja paralela à reta $-3x + 3y = 2026$.**

- Etapa 1: encontrar o coeficiente angular ($m_r$) da reta $r$: $-3x + 3y = 2026$.

$$
-3x + 3y = 2026 \rightarrow
3y = 3x + 2026  \rightarrow
$$

$$
y = \frac{3x}{3} + \frac{2026}{3} = x + \frac{2026}{3}
$$

Portanto, o coeficiente angular da reta $r$ é $m_r = 1$.

- Etapa 2: derivar a função $f(x)$.

A função "de dentro" é $g(x) = 1 + x^2$ e a função "de fora" é $h(x) = \ln x$.

$$
f(x) = \ln(1 + x^2)
$$

$$
f'(x) = \frac{1}{g(x)} \cdot g'(x) = 
\frac{g'(x)}{g(x)} = \frac{2x}{1 + x^2}
$$

- Etapa 3: igualar a derivada da função $f(x)$ ao coeficiente angular da reta $r$.

$$
f'(x) = m_r \Leftrightarrow \frac{2x_0}{1 + x_0^2} = 1
$$

$$
2x_0 = 1 + x_0^2
$$

$$
1 + x_0^2 - 2x_0 = 0
$$
Podemos fatorar:

$$
(x_0 - 1)^2 = 0
$$

$$
\sqrt{(x_0 - 1)^2} = \sqrt{0}
$$

$$
x_0 - 1 = 0 \rightarrow x_0 = 1
$$

Com isso, temos que $x_0 = 1$.


##  P.48
**Mostre que existem apenas duas retas tangentes ao gráfico de ..**

$$
f(x) = \frac{x^3}{3} - \frac{5}{2}\cdot x^2 + 8x + 99
$$

**.. que são paralelas à reta $r$: $y = 2x + 5$.**

- Etapa 1: encontrar o coeficiente angular ($m_r$) da reta $r$: 

$$m = 2$$


- Etapa 2: Estamos procurando todos os pontos $x_0$ tais que a derivada no ponto $x_0$ seja igual ao coeficiente angular da reta $r$. Portanto, precisamos derivar a função $f(x)$.


$$
f(x) = \frac{x^3}{3} - \frac{5}{2}\cdot x^2 + 8x + 99
$$

$$
f'(x) = \frac{1}{3} \cdot 3x^{3-1} - \frac{5}{2} \cdot 2x^{2-1} + 8
$$

$$
f'(x) = x^{2} - 5x + 8
$$

- Etapa 3: igualar a derivada da função $f(x)$ ao coeficiente angular da reta $r$.

$$
f'(x) = m_r \Leftrightarrow x^2 - 5x + 8 = 2
$$

$$
x^2 - 5x + 6 = 0
$$

Resolver as raízes:

$$
x^2 - 5x + 6 = 0 \rightarrow (x - 2)(x - 3) = 0
$$

Portanto as raízes são $x_1 = 2$ e $x_2 = 3$.


##  P.49
**Escreva a equação da reta tangente ao gráfico de $f(x) = \frac{x^2}{2} + 7$ que é paralela à reta $r$: $3x + 6y + 201 = 0$**

- Etapa 1: encontrar o coeficiente angular ($m_r$) da reta $r$: $3x + 6y + 201 = 0$.

$$
3x + 6y + 201 = 0 \rightarrow 6y = -3x - 201 
$$
$$
y = -\frac{3}{6}x - \frac{201}{6}
$$

$$
y =  -\frac{1}{2}x - \frac{201}{6}
$$

Logo $m_r = -\frac{1}{2}$.

- Etapa 2: Estamos procurando $x_0$ tal que $f'(x_0) = m_r = \frac{-1}{2}$. Portanto, precisamos derivar a função $f(x)$.

$$
f(x) = \frac{x^2}{2} + 7 = \frac{1}{2} \cdot x^2 + 7
$$

$$
f'(x) = \frac{1}{2} \cdot 2x^{2-1} + 0 = x
$$

Logo $f'(x_0) = x_0 = \frac{-1}{2}$.


- Etapa 3: precisamos escrever a equação da reta tangente. Lembremos de $y = m(x - x_0) + y_0$.

Considerando que:

- $m_r = -\frac{1}{2}$

- $x_0 = -\frac{1}{2}$

$$
y = y_0 +  m(x - x_0) 
$$

$$
y = f(x_0) + f'(x_0)(x - x_0)
$$

$$
y = (\frac{(-\frac{1}{2})^2}{2} + 7) + (-\frac{1}{2}) \cdot (x - (-\frac{1}{2}))
$$


$$
y = (\frac{\frac{1}{4}}{2} + 7) - \frac{1}{2} \cdot (x + \frac{1}{2})
$$


$$
y = (\frac{1}{4} \cdot \frac{1}{2} + 7) - \frac{1}{2} \cdot (x + \frac{1}{2})
$$

$$
y = (\frac{1}{8} + 7) - \frac{1}{2} \cdot (x + \frac{1}{2})
$$
